### ISSUE TITLE
Types error with emittery

### ISSUE THREAD

**Issue by OtaK** [sequelize/umzug#440] opened 2021-02-10 16:21 UTC
## Context 

- Version: 3.0.0-beta.15
- Storage: SequelizeStorage, but irrelevant
- Sequelize v6.5.0
- Node 14 LTS
- TypeScript

## Issue

```
node_modules/umzug/lib/umzug.d.ts:14:65 - error TS2315: Type 'Emittery' is not generic.

14 export declare class Umzug<Ctx extends object = object> extends emittery<UmzugEvents<Ctx>> {
                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error.
```

Seems like there's a problem with how you `import` things because it seems it's pulling the JS definition and not the TypeScript ones.

**Comment by mmkal** [comment] 2021-02-18 13:13
@OtaK I can't reproduce this - could you share your tsconfig?

Oh, one other possibility, since it's complaining about emittery: what version of emittery is being resolved from umzug (can check by using "Go to Definition" and looking at the emittery package.json)? Umzug depends on 0.8.1, but maybe if there's a custom module resolution pointing to an older version, it could be causing this issue for you.

You can also print the emittery version with the command line:

```bash
(cd node_modules/umzug; node -e 'var path=require("path"); var emittery=require.resolve("emittery"); console.log(require(path.join(path.dirname(emittery), "package.json")).version)')
```

**Comment by OtaK** [comment] 2021-02-21 14:01
That might probably it, since I use `jest` for my tests, which depends on `jest-runner`, which itself depends on `emittery@^0.7.1`.

Here are my compiler options:

```json 
{
    "compilerOptions": {
        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "noImplicitAny": true,
        "forceConsistentCasingInFileNames": true,
        "noEmitOnError": true,
        "noFallthroughCasesInSwitch": true,
        "noImplicitReturns": true,
        "pretty": true,
        "module": "CommonJS",
        "lib": ["ES2020", "esnext.asynciterable"],
        "target": "ES2020",
        "moduleResolution": "node",
        "incremental": true,
        "sourceMap": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "allowSyntheticDefaultImports": true,
        "esModuleInterop": true,
        "outDir": "build",
        "baseUrl": ".",
        "paths": {
            "*": [
                "node_modules/*",
                "src/lib/*",
                "types/*.d.ts"
            ]
        },
        "newLine": "LF"
    },
   ...
}
```

**Comment by mmkal** [comment] 2021-05-16 16:06
npm/yarn should be able to resolve this. If this is still an issue for you, can you make a small reproducible example?

**Comment by mmkal** [comment] 2021-07-28 20:22
Closing - feel free to write here if you're able to provide a reproduction.

**Closed by mmkal** 2021-07-28 20:22 UTC
